=== publicground/poc-gzac-bestanden/gzac-sd-zgw-backend/src/main/resources/config/document/definition/reference/sd/persoon-sd-v2.schema.json
{
    "$id": "persoon.schema",
    "type": "object",
    "title": "Persoon",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "voorletters": {
            "type": "string"
        },
        "voornamen": {
            "type": "string"
        },
        "voorvoegsel": {
            "type": "string"
        },
        "achternaam": {
            "type": "string"
        },
        "volledigeNaam": {
            "type": "string"
        },
        "geboortedatum": {
            "type": "string"
        },
        "communicatievoorkeur": {
            "type": "string",
            "enum": [
                "portaal",
                "post"
            ]
        },
        "bsn": {
            "$ref": "/document/definition/reference/ontologie/persoonsgegevens-v1.schema.json#/definitions/bsn"
        },
        "anummer": {
            "description": "<p>Het administratienummer van een PERSOON binnen de gemeentelijke basisadministratie (GBA), zoals bedoeld als in artikel 50 van de Wet GBA.</p><br/><p>Norminstantie: GBA</p><br/>",
            "type": "string"
        },
        "codeBrpGegevensGeheim": {
            "type": "string",
            "enum": [
                "GEEN_GEHEIMHOUDING",
                "GEGEVENS_GEHEIM",
                "NIET_KERKEN",
                "NIET_VRIJE_DERDEN",
                "NIET_KERKEN_DERDEN",
                "NIET_DERDEN_ALGEMEEN",
                "NIET_KERKEN_VRIJE_DERDEN",
                "NIET_KERKEN_VRIJE_DERDEN_ALGEMEEN_DERDEN"
            ]
        },
        "naamgebruik": {
            "type": "string"
        },
        "geslachtsAanduiding": {
            "type": "string"
        },
        "geslachtsnaamPartner": {
            "type": ["string", "null"]
        },
        "ingangsdatumHuwelijk": {
            "type": "string"
        },
        "contactgegevens": {
            "type": "object",
            "properties": {
                "email": {
                    "anyOf": [
                        {
                            "type": "string",
                            "pattern": "^[A-Za-z0-9_-]+([.][A-Za-z0-9_-]+)*@[A-Za-z0-9_-]+([.][A-Za-z0-9_-]+)*[.][A-Za-z0-9]+$"
                        },
                        {
                            "type": "string",
                            "enum": [
                                ""
                            ]
                        }
                    ]
                },
                "telefoon": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "adresBrp": {
            "$ref": "/document/definition/reference/sd/adres-sd-v2.schema.json#/definitions/adres"
        },
        "postadresBrp": {
            "$ref": "/document/definition/reference/sd/adres-sd-v1.schema.json#/definitions/adres"
        },
        "postadres": {
            "$ref": "/document/definition/reference/sd/adres-sd-v1.schema.json#/definitions/adres"
        },
        "verblijfadres": {
            "$ref": "/document/definition/reference/sd/adres-sd-v2.schema.json#/definitions/adres"
        },
        "correspondentieadres": {
            "type": "string",
            "enum": [
                "adresBrp",
                "postadresBrp",
                "verblijfadres"
            ]
        },
        "woonsituatie": {
            "type": "string",
            "enum": [
                "BRP",
                "PARTNER_INWONEND",
                "ELDERS",
                "DETENTIE",
                "DAKLOOS",
                "ONBEKEND"
            ]
        },
        "redenNietIngeschrevenOpVerblijfadres": {
            "type": "string"
        },
        "toelichtingNietIngeschrevenOpVerblijfadres": {
            "type": "string"
        },
        "verblijfstitel": {
            "type": "object",
            "properties": {
                "verblijfstitelId": {
                    "description": "Uniek nummer toegekend door het systeem, zodat een verblijfstitel kan wroden geidentificeerd.",
                    "$ref": "/document/definition/reference/ontologie/persoonsgegevens-v1.schema.json#/definitions/guid"
                },
                "codeVerblijfstitel": {
                    "description": "<p>Code die een aanduiding geeft van de juridische grondslag op basis waarvan een persoon als bedoeld in de Vreemdelingenwet in Nederland verblijft.</p><br/><p>Bron: SGR 16.0, gebaseerd op NEN 1888:2002 - Verblijfstitel.</p><p>Tabel 56 - Verblijfstiteltabel (RVIG landelijke tabellen).</p><br/><p>Opmerking :</p><ul>                              </ul>",
                    "type": ["object", "null"]
                },
                "datumAanvangVerblijfstitel": {
                    "description": "<p>De datum van de eerste dag waarop de VERBLIJFSTITEL van toepassing is.</p><br/><p>Norminstantie: UGR</p>",
                    "$ref": "/document/definition/reference/ontologie/persoonsgegevens-v1.schema.json#/definitions/datum"
                },
                "datumEindeVerblijfstitel": {
                    "description": "<p>De datum van de laatste dag waarop de VERBLIJFSTITEL van toepassing is.</p><br/><p>Norminstantie: UGR</p>",
                    "$ref": "/document/definition/reference/ontologie/persoonsgegevens-v1.schema.json#/definitions/datum"
                }
            }
        },
        "verblijfplaatsHistorisch": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/verblijfplaats"
            }
        },
        "nationaliteiten": {
            "type": "array",
            "items": {
                "type": "object",
                "$ref": "/document/definition/reference/sd/nationaliteit-sd-v1.schema.json#/definitions/cdNationaliteit"
            }
        },
        "nationaliteitOfVerblijfsstatus": {
            "type": ["string", "null"],
            "enum": [
                "NEDERLANDSE_NATIONALITEIT",
                "EU_ONDERDAAN",
                "GELDIGE_VERBLIJFSVERGUNNING",
                "GEEN_VERBLIJFSVERGUNNING",
                "VERLOPEN_VERBLIJFSVERGUNNING",
                "IS_GEEN_NEDERLANDER",
                null
            ]
        },
        "actiesVerblijfstatus": {
            "type": "string",
            "enum": [
                "VERLENGING_VERBLIJFSDOCUMENT_AANGEVRAAGD",
                "BEZWAAR_AFWIJZING",
                "GEEN"
            ]
        },
        "identiteitsbewijsGeupload": {
            "type": "boolean"
        },
        "partnerIsOndernemer": {
            "type": "boolean"
        },
        "zeldeAdresAlsAanvrager": {
            "type": "boolean"
        },
        "kinderenBsns": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "partnerBsn": {
            "type": "string"
        },
         "datumOverlijden": {
            "type": "string"
        },
        "heeftPartner": {
            "type": "string",
            "enum": [
                "JA",
                "NEE"
            ]
        },
        "heeftThuiswonendeKinderen": {
            "type": "string",
            "enum": [
                "JA",
                "NEE"
            ]
        },
        "uOfUwPartnerHeeftNietDeNederlandseNationaliteit": {
            "type": "string",
            "enum": [
                "JA",
                "NEE"
            ]
        },
        "relaties": {
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "$ref": "/document/definition/reference/sd/relatie-sd-v1.schema.json"
            }
        }
    },
    "definitions": {
        "verblijfplaats": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "WOONADRES",
                        "POSTADRES"
                    ]
                },
                "adres": {
                    "$ref": "/document/definition/reference/sd/adres-sd-v1.schema.json#/definitions/adres"
                },
                "datumBeginAdreshouding": {
                    "type": "string"
                }
            }
        }
    }
}

=== publicground/poc-gzac-bestanden/gzac-sd-zgw-backend/src/test/resources/suwinet/data/dtos/persoon_243000157.json
{
  "voornamen" : "Catharina jong en woont thuis",
  "voorvoegsel" : "de",
  "achternaam" : "Jansen",
  "geboortedatum" : "2013-10-07",
  "bsn" : "243000157",
  "adresBrp" : {
    "straatnaam" : "Zomerdijkstraat",
    "huisnummer" : 19,
    "huisletter" : "C",
    "huisnummertoevoeging" : "Huis",
    "postcode" : "1079WZ",
    "woonplaatsnaam" : "Amsterdam",
    "aanduidingBijHuisnummer" : "",
    "locatieomschrijving" : ""
  },
  "postadresBrp" : {
    "straatnaam" : "",
    "huisnummer" : 0,
    "huisletter" : "",
    "huisnummertoevoeging" : "",
    "postcode" : "",
    "woonplaatsnaam" : "",
    "aanduidingBijHuisnummer" : "",
    "locatieomschrijving" : ""
  },
    "verblijfplaatsHistorisch": [
        {
            "type": "WOONADRES",
            "adres": {
                "postcode": "2511BT",
                "huisletter": "a",
                "huisnummer": 70,
                "straatnaam": "Spui",
                "woonplaatsnaam": "'s-Gravenhage",
                "locatieomschrijving": "",
                "huisnummertoevoeging": "Huis",
                "aanduidingBijHuisnummer": ""
            },
            "datumBeginAdreshouding": "2025-12-09"
        },
        {
            "type": "POSTADRES",
            "adres": {
                "postcode": "2511BD",
                "huisletter": "",
                "huisnummer": 4,
                "straatnaam": "Lange Poten",
                "woonplaatsnaam": "Den Haag",
                "locatieomschrijving": "",
                "huisnummertoevoeging": "",
                "aanduidingBijHuisnummer": ""
            },
            "datumBeginAdreshouding": "2024-05-01"
        }
    ],
  "verblijfstitel" : {
    "codeVerblijfstitel" : {
      "code" : "41",
      "name" : ""
    },
    "datumAanvangVerblijfstitel" : "2012-09-15",
    "datumEindeVerblijfstitel" : "2024-09-15"
  },
  "nationaliteiten" : [ ],
  "kinderenBsns" : [ ],
  "partnerBsn" : "",
  "datumOverlijden" : ""
}

=== publicground/poc-gzac-bestanden/gzac-sd-zgw-backend/src/test/resources/suwinet/data/dtos/persoon_243000017.json
{
    "voornamen" : "Wilma woont niet meer thuis",
    "voorvoegsel" : "de",
    "achternaam" : "Jansen",
    "geboortedatum" : "2014-09-27",
    "bsn" : "243000017",
    "adresBrp" : {
        "straatnaam" : "kerkstraatstraat",
        "huisnummer" : 42,
        "huisletter" : "A",
        "huisnummertoevoeging" : "",
        "postcode" : "2011XB",
        "woonplaatsnaam" : "Den Haag",
        "aanduidingBijHuisnummer" : "",
        "locatieomschrijving" : ""
    },
    "postadresBrp" : {
        "straatnaam" : "",
        "huisnummer" : 0,
        "huisletter" : "",
        "huisnummertoevoeging" : "",
        "postcode" : "",
        "woonplaatsnaam" : "",
        "aanduidingBijHuisnummer" : "",
        "locatieomschrijving" : ""
    },
    "verblijfplaatsHistorisch": [
        {
            "type": "WOONADRES",
            "adres": {
                "postcode": "2511BT",
                "huisletter": "a",
                "huisnummer": 70,
                "straatnaam": "Spui",
                "woonplaatsnaam": "'s-Gravenhage",
                "locatieomschrijving": "",
                "huisnummertoevoeging": "Huis",
                "aanduidingBijHuisnummer": ""
            },
            "datumBeginAdreshouding": "2025-12-09"
        },
        {
            "type": "POSTADRES",
            "adres": {
                "postcode": "2511BD",
                "huisletter": "",
                "huisnummer": 4,
                "straatnaam": "Lange Poten",
                "woonplaatsnaam": "Den Haag",
                "locatieomschrijving": "",
                "huisnummertoevoeging": "",
                "aanduidingBijHuisnummer": ""
            },
            "datumBeginAdreshouding": "2024-05-01"
        }
    ],
    "verblijfstitel" : {
        "codeVerblijfstitel" : {
            "code" : "41",
            "name" : ""
        },
        "datumAanvangVerblijfstitel" : "2012-09-15",
        "datumEindeVerblijfstitel" : "2024-09-15"
    },
    "nationaliteiten" : [ ],
    "kinderenBsns" : [ ],
    "partnerBsn" : "",
    "datumOverlijden" : ""
}

=== publicground/poc-gzac-bestanden/gzac-sd-zgw-backend/src/test/resources/suwinet/data/dtos/persoon_444444440_no_partner.json
{
    "voornamen" : "Martin Maarten",
    "voorvoegsel" : "de",
    "achternaam" : "Visser",
    "geboortedatum" : "1944-06-11",
    "bsn" : "444444440",
    "adresBrp" : {
        "straatnaam" : "Zomerdijkstraat",
        "huisnummer" : 19,
        "huisletter" : "G",
        "huisnummertoevoeging" : "III",
        "postcode" : "1079WZ",
        "woonplaatsnaam" : "Amsterdam",
        "aanduidingBijHuisnummer" : "de trekbel",
        "locatieomschrijving" : "Bij het hek recht omhoog"
    },
    "postadresBrp" : {
        "straatnaam" : "",
        "huisnummer" : 0,
        "huisletter" : "",
        "huisnummertoevoeging" : "",
        "postcode" : "",
        "woonplaatsnaam" : "",
        "aanduidingBijHuisnummer" : "",
        "locatieomschrijving" : ""
    },
    "verblijfplaatsHistorisch": [
        {
            "type": "WOONADRES",
            "adres": {
                "postcode": "2511BT",
                "huisletter": "a",
                "huisnummer": 70,
                "straatnaam": "Spui",
                "woonplaatsnaam": "'s-Gravenhage",
                "locatieomschrijving": "",
                "huisnummertoevoeging": "Huis",
                "aanduidingBijHuisnummer": ""
            },
            "datumBeginAdreshouding": "2025-12-09"
        },
        {
            "type": "POSTADRES",
            "adres": {
                "postcode": "2511BD",
                "huisletter": "",
                "huisnummer": 4,
                "straatnaam": "Lange Poten",
                "woonplaatsnaam": "Den Haag",
                "locatieomschrijving": "",
                "huisnummertoevoeging": "",
                "aanduidingBijHuisnummer": ""
            },
            "datumBeginAdreshouding": "2024-05-01"
        }
    ],
    "verblijfstitel" : {
        "codeVerblijfstitel" : {
            "code" : "-1",
            "name" : ""
        },
        "datumAanvangVerblijfstitel" : "",
        "datumEindeVerblijfstitel" : ""
    },
    "nationaliteiten" : [ ],
    "kinderenBsns" : [ ],
    "datumOverlijden" : ""
}

=== publicground/poc-gzac-bestanden/gzac-sd-zgw-backend/src/test/resources/suwinet/data/dtos/persoon_111111110_met_kinderen.json
{
    "voornamen" : "Henk",
    "voorvoegsel" : "de",
    "achternaam" : "Jansen",
    "geboortedatum" : "1960-07-20",
    "bsn" : "111111110",
    "adresBrp" : {
        "straatnaam" : "Zomerdijkstraat",
        "huisnummer" : 19,
        "huisletter" : "C",
        "huisnummertoevoeging" : "Huis",
        "postcode" : "1079WZ",
        "woonplaatsnaam" : "Amsterdam",
        "aanduidingBijHuisnummer" : "",
        "locatieomschrijving" : ""
    },
    "postadresBrp" : {
        "straatnaam" : "Kerkstraat",
        "huisnummer" : 79,
        "huisletter" : "A",
        "huisnummertoevoeging" : "Huis",
        "postcode" : "2054RC",
        "woonplaatsnaam" : "Utrecht",
        "aanduidingBijHuisnummer" : "",
        "locatieomschrijving" : ""
    },
    "verblijfplaatsHistorisch": [
        {
            "type": "WOONADRES",
            "adres": {
                "postcode": "2511BT",
                "huisletter": "a",
                "huisnummer": 70,
                "straatnaam": "Spui",
                "woonplaatsnaam": "'s-Gravenhage",
                "locatieomschrijving": "",
                "huisnummertoevoeging": "Huis",
                "aanduidingBijHuisnummer": ""
            },
            "datumBeginAdreshouding": "2025-12-09"
        },
        {
            "type": "POSTADRES",
            "adres": {
                "postcode": "2511BD",
                "huisletter": "",
                "huisnummer": 4,
                "straatnaam": "Lange Poten",
                "woonplaatsnaam": "Den Haag",
                "locatieomschrijving": "",
                "huisnummertoevoeging": "",
                "aanduidingBijHuisnummer": ""
            },
            "datumBeginAdreshouding": "2024-05-01"
        }
    ],
    "verblijfstitel" : {
        "codeVerblijfstitel" : {
            "code" : "41",
            "name" : ""
        },
        "datumAanvangVerblijfstitel" : "2012-09-15",
        "datumEindeVerblijfstitel" : "2024-09-15"
    },
    "nationaliteiten" : [ ],
    "kinderenBsns" : [ "243000157", "243000017", "010002546", "080000071" ],
    "partnerBsn" : "999991954",
    "datumOverlijden" : ""
}
